version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hms
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hms-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Bloodbank@123
      MSSQL_MEMORY_LIMIT_MB: 512
    ports:
      - "1433:1433"
    volumes:
    - sqlserver_data:/var/opt/mssql
    networks:
      - hms-net

  backend:
    image: prathamaher/hms-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - hms-net

  bloodbank:
    image: prathamaher/bloodbank-service:latest
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    networks:
      - hms-net

  frontend:
    image: prathamaher/hms-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - bloodbank
    networks:
      - hms-net

volumes:
  mysql_data:
  sqlserver_data:

networks:
  hms-net:
